"""add google oauth fields to users

Revision ID: af8a57f03679
Revises: 34ac199cc409
Create Date: 2026-08-18 10:18:43.935193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8a57f03679'
down_revision = '34ac199cc409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=False, server_default='local'))
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])
        batch_op.alter_column('auth_provider', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_google_id', type_='unique')
        batch_op.drop_column('google_id')
        batch_op.drop_column('auth_provider')

    # ### end Alembic commands ###
