"""add contact_number to service_requests and complaints

Revision ID: b3f7a1c9d2e4
Revises: 7c1e9b2a5df0
Create Date: 2026-08-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f7a1c9d2e4'
down_revision = '7c1e9b2a5df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Pakistani contact number (11 digits, must start with '03') captured on
    # every service request and complaint so agents/supervisors/admins can
    # always reach the customer. Backfilled with a placeholder for any
    # pre-existing rows, then the server default is dropped so the
    # application is fully responsible for supplying a real value going
    # forward, matching the model definition.
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=11), nullable=False, server_default='03000000000'))
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.alter_column('contact_number', server_default=None)

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=11), nullable=False, server_default='03000000000'))
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('contact_number', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_column('contact_number')

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('contact_number')
    # ### end Alembic commands ###
